"""create users table

Revision ID: 8b1728450823
Revises: 
Create Date: 2025-05-01 17:47:06.184847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1728450823'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('ix_pills_id', table_name='pills')
    op.drop_table('pills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dl_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dl_material', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dl_company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('di_company_mf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('di_class_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('di_etc_otc_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('di_edi_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('item_seq', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('img_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pills_pkey'),
    sa.UniqueConstraint('class_id', name='pills_class_id_key')
    )
    op.create_index('ix_pills_id', 'pills', ['id'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
