"""add nose_vectors

Revision ID: f9982c5c2c64
Revises: dd6c5593c8ff
Create Date: 2025-05-04 05:47:20.475658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9982c5c2c64'
down_revision: Union[str, None] = 'dd6c5593c8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nose_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id')
    )
    op.create_index(op.f('ix_nose_vectors_id'), 'nose_vectors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nose_vectors_id'), table_name='nose_vectors')
    op.drop_table('nose_vectors')
    # ### end Alembic commands ###
